name: dart_ai_api
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  dart_openai: ^4.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  supabase: ^1.11.9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
